/**
 * Default lookup data for seeding lookup_cities and lookup_categories.
 * Cities: union of all mobile app sources (forms + listing filters).
 */

function uniqSort(arr) {
  return [...new Set(arr.map((s) => String(s).trim()).filter(Boolean))].sort((a, b) =>
    a.localeCompare(b)
  );
}

// BusinessSubmissionForm + ProductListingScreen-style extras (Filtu/Foltu, Xawaalad, Bank, etc.)
const citiesParts = [
  "Jigjiga",
  "Harar",
  "Diridhaba",
  "Addis Ababa",
  "Wajaale",
  "Shinniile",
  "Dhagaxbuur",
  "Qabridahar",
  "Godey",
  "Shilaabo",
  "Wardheer",
  "Dhanaan",
  "Iimay bari",
  "Iimay galbeed",
  "Fiiq",
  "Dhuxun",
  "Garbo",
  "Lehelow",
  "Jarrati",
  "Hargeelle",
  "Doolow",
  "Foltu",
  "Filtu",
  "Lay",
  "Nagayle",
  "Godcusbo",
  "Ceelwayne",
  "Boorama",
  "Hargaysa",
  "Saylac",
  "Gabilay",
  "Berbera",
  "Sheekh",
  "Burco",
  "Laascaanood",
  "Buuhoodle",
  "Ceerigaabo",
  "Boosaaso",
  "Qardho",
  "Garoowe",
  "Gaalkacyo",
  "Burtinle",
  "Cadaado",
  "Dhuusamareeb",
  "Guriceel",
  "Beledwayne",
  "Buulaburde",
  "Jawhar",
  "Muqdisho",
  "Balcad",
  "Afgooye",
  "Kismaayo",
  "Marka",
  "Baraawe",
  "Garbaharray",
  "Baydhabo",
  "Xudur",
  "Wanlawayn",
  "Buulamareer",
  "Afmadow",
  "Dhoobley",
  "Badhaaadhe",
  "Nairobi",
  "Wajeer",
  "Gaarisa",
  "Mandheera",
  "Mooyaale",
  "Qoloji",
  "Baabili",
  "Mombasa",
  "Libooyo",
  "Xawaalad",
  "Bank",
  "Other",
];

exports.defaultCities = uniqSort(citiesParts);

// BusinessSubmissionForm `businessCategories`
exports.businessCategories = uniqSort([
  "Agab beer",
  "Bagaash",
  "Beeralay",
  "Bookshop",
  "Carwo",
  "Caanoole",
  "Celis-used",
  "Cosmetics",
  "Cypersecuriy",
  "Dawaarle",
  "Dhar jumlo",
  "Dhar tafaariiq",
  "Dhisme",
  "Digaag",
  "Doobi/Lamadaayo",
  "Electrics",
  "Electronics",
  "Equipment",
  "Fadhi kaliya",
  "Farmashi",
  "Farsamo",
  "Financial services",
  "Foorno",
  "Gaadiid",
  "Garaash",
  "Garoon ciyaar",
  "Gym and fitness",
  "Hilible",
  "Hotel",
  "Huudhay",
  "Hypermarket",
  "Internet",
  "Isbitaal",
  "Isgaadhsiin",
  "Iskuul",
  "IT Support",
  "Jaamacad",
  "Kaalin shidaal",
  "Kafateria",
  "Kalluunle",
  "Logistics",
  "Machad",
  "Machinery",
  "Madbacad",
  "Maktabad",
  "Maqaaxi",
  "Maacuun",
  "Meherad Shaah",
  "Metaverse",
  "Microfinance",
  "Nadaafad",
  "NGO",
  "Online edu",
  "Ookiyaallo",
  "Other",
  "Photo shop",
  "Raashin",
  "Real Estate",
  "Sariiro/fadhi",
  "Sariiro kaliya",
  "Sharaab",
  "Shinniile",
  "Spare part",
  "Subagle",
  "Supermarket",
  "Suug gayn",
  "Teknoolaji",
  "Tima jare",
  "Transport",
  "Travel agency",
  "Warshad",
  "Xaraash",
  "Xoolo",
]);

// ProductListingScreen filter categories (without "All"), plus align with product forms
exports.productCategories = uniqSort([
  "Electronics",
  "Electrics",
  "Dhisme",
  "Nadaafad",
  "Dhar jumlo",
  "Dhar tafaariiq",
  "Sharaab",
  "Bagaash",
  "Maacuun",
  "Sariiro/fadhi",
  "Sariiro kaliya",
  "Fadhi kaliya",
  "Maqaaxi",
  "Kafateria",
  "Real Estate",
  "Gaadiid",
  "Maktabad",
  "Bookshop",
  "Beeralay",
  "Shinniile",
  "Kalluunle",
  "Dawaarle",
  "Agab beer",
  "Warshad",
  "Financial services",
  "Teknoolaji",
  "Saxaafad",
  "Iskuul",
  "Jaamacad",
  "Machad",
  "Farmashi",
  "Transport",
  "Logistics",
  "Isgaadhsiin",
  "Internet",
  "Equipment",
  "Machinery",
  "Hotel",
  "Carwo",
  "Supermarket",
  "Hypermarket",
  "Garaash",
  "Metaverse",
  "Madbacad",
  "Kaalin shidaal",
  "Spare part",
  "Tima jare",
  "Meherad Shaah",
  "Isbitaal",
  "Farsamo",
  "Doobi/Lamadaayo",
  "Cosmetics",
  "Foorno",
  "Microfinance",
  "IT Support",
  "Cypersecuriy",
  "Suug gayn",
  "Photo shop",
  "Online edu",
  "Garoon ciyaar",
  "Gym and fitness",
  "Travel agency",
  "Xaraash",
  "Huudhay",
  "Celis-used",
  "Xoolo",
  "Caanoole",
  "Subagle",
  "Hilible",
  "Digaag",
  "NGO",
  "Raashin",
  "Ookiyaallo",
  "Xawaalad",
  "Bank",
  "Other",
]);

exports.professionCategories = uniqSort([
  "Doctor",
  "Tagsiile",
  "Engineer",
  "Farsamo",
  "Qareen",
  "La-taliye",
  "Dullaal",
  "Macalin",
  "Naqshadeeye",
  "Artist",
  "Suuq geeye",
  "Xisaabiye",
  "Auditor",
  "Developer",
  "Dayactire",
  "Darawal",
  "Xoolo daweeye",
  "Shiini yaqaan",
  "Saxafi",
  "Wariye",
  "Bajaajle",
  "Tuubiiste",
  "Dab yaqaan",
  "Cilmi baashe",
  "Wakiil",
  "Soo adeege",
  "Makaanik",
  "Matoriste",
  "Alxanle",
  "Qawsaar",
  "Xidhaale",
  "Beer yaqaan",
  "Sayladle",
  "Turjumaan",
  "Camera man",
  "Tifatire",
  "Dhuxulle",
  "Farayaamo",
  "Najaar",
  "Wastaad",
  "Kuuli",
  "Tima jare",
  "Cook",
  "Cunta kariye",
  "Kabalyeeri",
  "Kaba tole",
  "Dawaarle",
  "Baariste",
  "Kawaanle",
  "Other",
]);
